# Generated by Django 2.1.5 on 2019-01-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_column='result:date', default=False)),
                ('price', models.FloatField(blank=True, db_column='result:price', null=True)),
                ('property_id', models.IntegerField(blank=True, db_column='result:id', null=True)),
                ('favourite', models.BooleanField(default=False)),
                ('best', models.BooleanField(default=False)),
            ],
        ),
    ]
