# Generated by Django 2.1.5 on 2019-01-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_auto_20190108_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultproperty',
            name='title',
            field=models.CharField(default='Title ERROR', max_length=60),
        ),
    ]
